apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-world
  labels:
    app: minecraft
  annotations:
    kubesailEditorUid: d19fb82f-cd21-4d11-88d3-df2b07814054
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
